name: 13.13.0 Customer Provided Docker Image

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/included:13.13.0
    strategy: 
      fail-fast: false
      matrix:
        containers: [1, 2]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}